# Generated by Django 3.1.3 on 2020-12-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('car_price', models.IntegerField()),
                ('car_desc', models.CharField(max_length=500)),
                ('car_image', models.ImageField(upload_to='home/images')),
            ],
        ),
    ]
