# Generated by Django 3.1.3 on 2020-12-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
