# Generated by Django 3.1.3 on 2020-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201220_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corder',
            fields=[
                ('Corder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('pickup_date', models.DateField()),
                ('pickup_address', models.CharField(max_length=100)),
            ],
        ),
    ]
