# Generated by Django 3.1.3 on 2021-01-04 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201221_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 9, 3, 47, 420303)),
        ),
    ]
