# Generated by Django 3.1.3 on 2021-01-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_corder_drop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 20, 24, 32, 4286)),
        ),
    ]
