# Generated by Django 3.1.3 on 2021-01-05 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210105_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='corder',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 23, 4, 0, 699029)),
        ),
    ]
