# Generated by Django 3.1.3 on 2021-01-05 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210105_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corder',
            name='total',
        ),
        migrations.AddField(
            model_name='corder',
            name='n',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 23, 21, 39, 714635)),
        ),
    ]
