# Generated by Django 3.1.3 on 2021-01-05 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210105_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corder',
            old_name='n',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 23, 55, 46, 682815)),
        ),
    ]
