# Generated by Django 3.1.3 on 2021-01-05 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210106_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corder',
            name='total',
        ),
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 1, 6, 59, 139642)),
        ),
    ]
