# Generated by Django 3.1.3 on 2021-01-06 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210106_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='to_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='tiwari', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='pass1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='sudhanshu', max_length=100),
        ),
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 11, 3, 34, 453866)),
        ),
    ]
