# Generated by Django 3.2.5 on 2021-07-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210106_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 19, 26, 2, 575836)),
        ),
    ]
