# Generated by Django 3.2.5 on 2021-08-02 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_corder_drop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corder',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 21, 22, 47, 847306)),
        ),
    ]
